### ISSUE TITLE
auto_tweet failing on blackout dates

### ISSUE THREAD

**Issue by jrgant** [SERTwitter/ser#20]
https://github.com/SERTwitter/ser/blob/edfe510e838309ea8a951b4f55de13f77605c553/R/auto_tweet.R#L160-L176

`blackout_tweet()` is used as `post_tweet_of_type()` on weekends. However, it fails without arguments for `tweet_hist_id` and `twitter_token`. No public-facing issues here because nothing is tweeted on blackout days, but we get an error message via email when this action fails.

tldr: The arguments to `blackout_tweet()` should match those of `post_tweet_library()`

**Comment by malcolmbarrett** [comment]
You could also just add `...` to `blackout_tweet()` to catch extra unused arguments in this case

**Comment by jrgant** [comment]
Good thought, thanks. `retweet_queue` is failing too right now, I think for the same reason. I'll take care of it.
